<a href="https://colab.research.google.com/github/kiranmayi19/basicml/blob/main/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
features=['SepalLengthCm',	'SepalWidthCm',	'PetalLengthCm',	'PetalWidthCm']
x=df.loc[:,features].values
y=df.loc[:,['Species']].values

In [6]:
x=StandardScaler().fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [9]:
pca=PCA(n_components=2)
principalComponents=pca.fit_transform(x)
df_pca=pd.DataFrame(data=principalComponents,columns=['principal component 1','principal component 2'])
df_pca.head()

   principal component 1  principal component 2
0              -2.264542               0.505704
1              -2.086426              -0.655405
2              -2.367950              -0.318477
3              -2.304197              -0.575368
4              -2.388777               0.674767

In [10]:
finalDf=pd.concat([df_pca,df['Species']],axis=1)
finalDf.head()

   principal component 1  principal component 2      Species
0              -2.264542               0.505704  Iris-setosa
1              -2.086426              -0.655405  Iris-setosa
2              -2.367950              -0.318477  Iris-setosa
3              -2.304197              -0.575368  Iris-setosa
4              -2.388777               0.674767  Iris-setosa

In [11]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model=model.fit(df_pca,y.ravel())
y_predict=model.predict(df_pca)
Actual_predicted=pd.DataFrame({'predict':y_predict.flatten(),'Actual':y.flatten()})
Actual_predicted.head()

       predict       Actual
0  Iris-setosa  Iris-setosa
1  Iris-setosa  Iris-setosa
2  Iris-setosa  Iris-setosa
3  Iris-setosa  Iris-setosa
4  Iris-setosa  Iris-setosa

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_predict)

0.8933333333333333

In [13]:
model1=GaussianNB()
model1=model.fit(x,y.ravel())
y_predict1=model.predict(x)
Actual_predicted=pd.DataFrame({'predict':y_predict1.flatten(),'Actual':y.flatten()})
Actual_predicted.head()

       predict       Actual
0  Iris-setosa  Iris-setosa
1  Iris-setosa  Iris-setosa
2  Iris-setosa  Iris-setosa
3  Iris-setosa  Iris-setosa
4  Iris-setosa  Iris-setosa

In [14]:
accuracy_score(y,y_predict1)

0.96